In [61]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf

# physical_devices = tf.config.list_physical_devices("GPU")
# tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [62]:
#### initialization of tensors
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)

x = tf.ones((3, 3))
print(x)

x = tf.zeros((2, 3))
print(x)

x = tf.eye(3)
print(x)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print(x)

x = tf.random.uniform((1, 3), minval=0, maxval=1)
print(x)

x = tf.range(start=1, limit=10, delta=2)
print(x)

x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.26059017 -1.1540426  -0.72014076]
 [-2.953965   -0.9442258   0.5967369 ]
 [-1.1591388   2.0547345  -0.91220784]], shape=(3, 3), dtype=float32)
tf.Tensor([[0.81234777 0.65391314 0.70339656]], shape=(1, 3), dtype=float32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


In [63]:
#### mathematical operations
## element wise
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
z = tf.add(x, y)
print(tf.add(x, y))
print(x + y)
print(tf.subtract(x, y))
print(x - y)
print(tf.multiply(x, y))
print(x * y)
print(tf.divide(x, y))
print(x / y)
print(tf.tensordot(x, y, axes=1))
print(tf.reduce_sum(x * y))
print(x**5)

## matrix operation
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
print(tf.matmul(x, y))
print(x @ y)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[-1.2558364  1.504736   2.3037724  0.5698896]
 [ 2.0329123 -1.6721271 -4.0269356 -1.9388466]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-1.2558364  1.504736   2.3037724  0.5698896]
 [ 2.0329123 -1.6721271 -4.0269356 -1.9388466]], shape=(2, 4), dtype=float32)


In [64]:
# indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

x = tf.constant([[1, 2], [3, 4], [5, 6]])
print(x)
print(x[0])
print(x[0, :])
print(x[0:2])
print(x[0:2, :])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [65]:
# reshaping
x = tf.range(9)
print(x)
print(tf.reshape(x, (3, 3)))

x = tf.reshape(x, (3, 3))
print(tf.transpose(x))
print(tf.transpose(x, perm=[1, 0]))

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
